name: Testing Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

  docker:
    runs-on: ubuntu-22.04

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aranchoa
          password: dckr_pat_aen-8BKARociY-Wg0Lh-XFISihw
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest